language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
#  - python ./lowkey-examples/setup.py install
# command to run tests
script:
  - pytest ./lowkey/lww/tests/TestSuite.py
  - pytest ./lowkey/collabtypes/TestSuite.py
#  - pytest ./lowkey-examples/mindmap/tests/TestSuite.py