language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest ./collabserver-modeling/lww/tests/TestSuite.py
  - pytest ./collabserver-modeling/mindmap/tests/TestSuite.py